"""initial schema

Revision ID: 94b9d0bbece0
Revises: 
Create Date: 2026-09-18 23:51:37.689428
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '94b9d0bbece0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('app_settings',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('teacher_name', sa.String(length=120), nullable=False),
    sa.Column('model_name', sa.String(length=120), nullable=True),
    sa.Column('model_base_url', sa.String(length=500), nullable=True),
    sa.Column('api_key_ref', sa.String(length=255), nullable=True),
    sa.Column('storage_root', sa.String(length=500), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=True),
    sa.Column('queue_limit', sa.Integer(), nullable=False),
    sa.Column('worker_concurrency', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('event_name', sa.String(length=120), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('request_id', sa.String(length=128), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_user_created', 'audit_logs', ['user_id', 'created_at'], unique=False)
    op.create_table('classes',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('owner_user_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_user_id', 'name', 'status', name='uq_classes_owner_name_status')
    )
    op.create_table('review_records',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('before_json', sa.Text(), nullable=True),
    sa.Column('after_json', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_review_records_entity_created', 'review_records', ['entity_type', 'entity_id', 'created_at'], unique=False)
    op.create_table('rubrics',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('owner_user_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('subject', sa.String(length=32), nullable=False),
    sa.Column('question_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('remember_me', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.String(length=40), nullable=False),
    sa.Column('revoked_at', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('last_seen_at', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('assignment_batches',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('owner_user_id', sa.String(length=64), nullable=False),
    sa.Column('class_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('subject', sa.String(length=32), nullable=False),
    sa.Column('total_score', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('current_revision', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.Column('archived_at', sa.String(length=40), nullable=True),
    sa.CheckConstraint('total_score > 0', name='ck_assignment_batches_total_score_positive'),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_batches_owner_status_updated', 'assignment_batches', ['owner_user_id', 'status', 'updated_at'], unique=False)
    op.create_table('rubric_versions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('rubric_id', sa.String(length=64), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source_version_id', sa.String(length=64), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.CheckConstraint('total_score > 0', name='ck_rubric_versions_total_score_positive'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rubric_id'], ['rubrics.id'], ),
    sa.ForeignKeyConstraint(['source_version_id'], ['rubric_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rubric_id', 'version_no', name='uq_rubric_versions_no')
    )
    op.create_table('students',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('class_id', sa.String(length=64), nullable=False),
    sa.Column('student_code', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_id', 'student_code', name='uq_students_class_code')
    )
    op.create_index('ix_students_class_code', 'students', ['class_id', 'student_code'], unique=False)
    op.create_table('assignment_groups',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('batch_id', sa.String(length=64), nullable=False),
    sa.Column('student_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('grouping_confidence', sa.Numeric(precision=8, scale=5), nullable=True),
    sa.Column('grouping_reason', sa.String(length=500), nullable=True),
    sa.Column('confirmed_by', sa.String(length=64), nullable=True),
    sa.Column('confirmed_at', sa.String(length=40), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['assignment_batches.id'], ),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('batch_questions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('batch_id', sa.String(length=64), nullable=False),
    sa.Column('question_no', sa.String(length=32), nullable=False),
    sa.Column('question_type', sa.String(length=32), nullable=False),
    sa.Column('max_score', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reference_answer', sa.Text(), nullable=True),
    sa.Column('objective_rule_json', sa.Text(), nullable=True),
    sa.Column('rubric_version_id', sa.String(length=64), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.CheckConstraint('max_score > 0', name='ck_batch_questions_max_score_positive'),
    sa.ForeignKeyConstraint(['batch_id'], ['assignment_batches.id'], ),
    sa.ForeignKeyConstraint(['rubric_version_id'], ['rubric_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'question_no', name='uq_batch_questions_batch_no')
    )
    op.create_table('grading_runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('batch_id', sa.String(length=64), nullable=False),
    sa.Column('scope_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('rule_version', sa.String(length=120), nullable=False),
    sa.Column('model_name', sa.String(length=120), nullable=True),
    sa.Column('prompt_version', sa.String(length=120), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('finished_at', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['assignment_batches.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_exports',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('batch_id', sa.String(length=64), nullable=False),
    sa.Column('requested_by', sa.String(length=64), nullable=False),
    sa.Column('report_mode', sa.String(length=32), nullable=False),
    sa.Column('format', sa.String(length=16), nullable=False),
    sa.Column('scope_json', sa.Text(), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=True),
    sa.Column('failure_code', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('finished_at', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['assignment_batches.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rubric_points',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('rubric_version_id', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('max_score', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.CheckConstraint('max_score > 0', name='ck_rubric_points_max_score_positive'),
    sa.ForeignKeyConstraint(['rubric_version_id'], ['rubric_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_files',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('batch_id', sa.String(length=64), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('extension', sa.String(length=16), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('failure_code', sa.String(length=80), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.CheckConstraint('size_bytes > 0', name='ck_source_files_size_positive'),
    sa.ForeignKeyConstraint(['batch_id'], ['assignment_batches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index('ix_source_files_batch_sha256', 'source_files', ['batch_id', 'sha256'], unique=False)
    op.create_index('ix_source_files_batch_status', 'source_files', ['batch_id', 'status'], unique=False)
    op.create_table('grading_tasks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('grading_run_id', sa.String(length=64), nullable=False),
    sa.Column('assignment_group_id', sa.String(length=64), nullable=False),
    sa.Column('question_id', sa.String(length=64), nullable=False),
    sa.Column('task_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('locked_by', sa.String(length=120), nullable=True),
    sa.Column('heartbeat_at', sa.String(length=40), nullable=True),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['assignment_group_id'], ['assignment_groups.id'], ),
    sa.ForeignKeyConstraint(['grading_run_id'], ['grading_runs.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['batch_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_grading_tasks_status_created', 'grading_tasks', ['status', 'created_at'], unique=False)
    op.create_table('rubric_examples',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('rubric_version_id', sa.String(length=64), nullable=False),
    sa.Column('rubric_point_id', sa.String(length=64), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['rubric_point_id'], ['rubric_points.id'], ),
    sa.ForeignKeyConstraint(['rubric_version_id'], ['rubric_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_pages',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('source_file_id', sa.String(length=64), nullable=False),
    sa.Column('batch_id', sa.String(length=64), nullable=False),
    sa.Column('page_index', sa.Integer(), nullable=False),
    sa.Column('original_storage_key', sa.String(length=500), nullable=False),
    sa.Column('processed_storage_key', sa.String(length=500), nullable=True),
    sa.Column('transform_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.CheckConstraint('page_index >= 1', name='ck_source_pages_page_index_positive'),
    sa.ForeignKeyConstraint(['batch_id'], ['assignment_batches.id'], ),
    sa.ForeignKeyConstraint(['source_file_id'], ['source_files.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_file_id', 'page_index', name='uq_source_pages_file_index')
    )
    op.create_index('ix_source_pages_batch_status', 'source_pages', ['batch_id', 'status'], unique=False)
    op.create_table('anomalies',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('batch_id', sa.String(length=64), nullable=False),
    sa.Column('assignment_group_id', sa.String(length=64), nullable=True),
    sa.Column('source_page_id', sa.String(length=64), nullable=True),
    sa.Column('question_id', sa.String(length=64), nullable=True),
    sa.Column('anomaly_type', sa.String(length=80), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('evidence_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('resolved_at', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['assignment_group_id'], ['assignment_groups.id'], ),
    sa.ForeignKeyConstraint(['batch_id'], ['assignment_batches.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['batch_questions.id'], ),
    sa.ForeignKeyConstraint(['source_page_id'], ['source_pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_anomalies_batch_status_severity', 'anomalies', ['batch_id', 'status', 'severity'], unique=False)
    op.create_table('answer_versions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('assignment_group_id', sa.String(length=64), nullable=False),
    sa.Column('source_page_id', sa.String(length=64), nullable=False),
    sa.Column('question_id', sa.String(length=64), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('is_blank_confirmed', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=8, scale=5), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['assignment_group_id'], ['assignment_groups.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['batch_questions.id'], ),
    sa.ForeignKeyConstraint(['source_page_id'], ['source_pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ocr_runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('batch_id', sa.String(length=64), nullable=False),
    sa.Column('source_page_id', sa.String(length=64), nullable=False),
    sa.Column('engine_name', sa.String(length=80), nullable=False),
    sa.Column('engine_version', sa.String(length=160), nullable=False),
    sa.Column('preprocess_version', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('raw_output_storage_key', sa.String(length=500), nullable=True),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('started_at', sa.String(length=40), nullable=True),
    sa.Column('finished_at', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['assignment_batches.id'], ),
    sa.ForeignKeyConstraint(['source_page_id'], ['source_pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('page_groupings',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('source_page_id', sa.String(length=64), nullable=False),
    sa.Column('assignment_group_id', sa.String(length=64), nullable=True),
    sa.Column('student_id', sa.String(length=64), nullable=True),
    sa.Column('page_sequence', sa.Integer(), nullable=True),
    sa.Column('grouping_status', sa.String(length=40), nullable=False),
    sa.Column('grouping_confidence', sa.Numeric(precision=8, scale=5), nullable=True),
    sa.Column('grouping_reason', sa.String(length=500), nullable=True),
    sa.Column('confirmed_by', sa.String(length=64), nullable=True),
    sa.Column('confirmed_at', sa.String(length=40), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_group_id'], ['assignment_groups.id'], ),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source_page_id'], ['source_pages.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_page_id', name='uq_page_groupings_page')
    )
    op.create_index('ix_page_groupings_group_sequence', 'page_groupings', ['assignment_group_id', 'page_sequence'], unique=False)
    op.create_table('grading_results',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('grading_task_id', sa.String(length=64), nullable=False),
    sa.Column('assignment_group_id', sa.String(length=64), nullable=False),
    sa.Column('question_id', sa.String(length=64), nullable=False),
    sa.Column('answer_version_id', sa.String(length=64), nullable=False),
    sa.Column('rubric_version_id', sa.String(length=64), nullable=True),
    sa.Column('result_status', sa.String(length=32), nullable=False),
    sa.Column('suggested_score', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('teacher_score', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('ai_comment', sa.Text(), nullable=True),
    sa.Column('teacher_comment', sa.Text(), nullable=True),
    sa.Column('evidence_json', sa.Text(), nullable=True),
    sa.Column('deduction_json', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(length=120), nullable=True),
    sa.Column('prompt_version', sa.String(length=120), nullable=True),
    sa.Column('rule_version', sa.String(length=120), nullable=True),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['answer_version_id'], ['answer_versions.id'], ),
    sa.ForeignKeyConstraint(['assignment_group_id'], ['assignment_groups.id'], ),
    sa.ForeignKeyConstraint(['grading_task_id'], ['grading_tasks.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['batch_questions.id'], ),
    sa.ForeignKeyConstraint(['rubric_version_id'], ['rubric_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_grading_results_group_question_status', 'grading_results', ['assignment_group_id', 'question_id', 'result_status'], unique=False)
    op.create_table('ocr_blocks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('ocr_run_id', sa.String(length=64), nullable=False),
    sa.Column('source_page_id', sa.String(length=64), nullable=False),
    sa.Column('block_index', sa.Integer(), nullable=False),
    sa.Column('text_raw', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=8, scale=5), nullable=True),
    sa.Column('x1', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('y1', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('x2', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('y2', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('question_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['ocr_run_id'], ['ocr_runs.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['batch_questions.id'], ),
    sa.ForeignKeyConstraint(['source_page_id'], ['source_pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_answers',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('assignment_group_id', sa.String(length=64), nullable=False),
    sa.Column('question_id', sa.String(length=64), nullable=False),
    sa.Column('current_version_id', sa.String(length=64), nullable=False),
    sa.Column('answer_text_joined', sa.Text(), nullable=True),
    sa.Column('coverage_status', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['assignment_group_id'], ['assignment_groups.id'], ),
    sa.ForeignKeyConstraint(['current_version_id'], ['answer_versions.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['batch_questions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assignment_group_id', 'question_id', name='uq_question_answers_group_question')
    )
    op.create_table('grading_point_results',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('grading_result_id', sa.String(length=64), nullable=False),
    sa.Column('rubric_point_id', sa.String(length=64), nullable=False),
    sa.Column('suggested_score', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('teacher_score', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('deduction_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['grading_result_id'], ['grading_results.id'], ),
    sa.ForeignKeyConstraint(['rubric_point_id'], ['rubric_points.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grading_point_results')
    op.drop_table('question_answers')
    op.drop_table('ocr_blocks')
    op.drop_index('ix_grading_results_group_question_status', table_name='grading_results')
    op.drop_table('grading_results')
    op.drop_index('ix_page_groupings_group_sequence', table_name='page_groupings')
    op.drop_table('page_groupings')
    op.drop_table('ocr_runs')
    op.drop_table('answer_versions')
    op.drop_index('ix_anomalies_batch_status_severity', table_name='anomalies')
    op.drop_table('anomalies')
    op.drop_index('ix_source_pages_batch_status', table_name='source_pages')
    op.drop_table('source_pages')
    op.drop_table('rubric_examples')
    op.drop_index('ix_grading_tasks_status_created', table_name='grading_tasks')
    op.drop_table('grading_tasks')
    op.drop_index('ix_source_files_batch_status', table_name='source_files')
    op.drop_index('ix_source_files_batch_sha256', table_name='source_files')
    op.drop_table('source_files')
    op.drop_table('rubric_points')
    op.drop_table('report_exports')
    op.drop_table('grading_runs')
    op.drop_table('batch_questions')
    op.drop_table('assignment_groups')
    op.drop_index('ix_students_class_code', table_name='students')
    op.drop_table('students')
    op.drop_table('rubric_versions')
    op.drop_index('ix_batches_owner_status_updated', table_name='assignment_batches')
    op.drop_table('assignment_batches')
    op.drop_table('sessions')
    op.drop_table('rubrics')
    op.drop_index('ix_review_records_entity_created', table_name='review_records')
    op.drop_table('review_records')
    op.drop_table('classes')
    op.drop_index('ix_audit_logs_user_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('app_settings')
    op.drop_table('users')
    # ### end Alembic commands ###
