"""add generic task records

Revision ID: dba25e373ce7
Revises: 94b9d0bbece0
Create Date: 2026-09-19 00:40:14.792339
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'dba25e373ce7'
down_revision: Union[str, Sequence[str], None] = '94b9d0bbece0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('task_type', sa.String(length=40), nullable=False),
    sa.Column('batch_id', sa.String(length=64), nullable=True),
    sa.Column('assignment_group_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('stage', sa.String(length=80), nullable=False),
    sa.Column('progress_current', sa.Integer(), nullable=False),
    sa.Column('progress_total', sa.Integer(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_items_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('started_at', sa.String(length=40), nullable=True),
    sa.Column('finished_at', sa.String(length=40), nullable=True),
    sa.Column('worker_id', sa.String(length=120), nullable=True),
    sa.Column('heartbeat_at', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['assignment_group_id'], ['assignment_groups.id'], ),
    sa.ForeignKeyConstraint(['batch_id'], ['assignment_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tasks_batch_status', 'tasks', ['batch_id', 'status'], unique=False)
    op.create_index('ix_tasks_status_created', 'tasks', ['status', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tasks_status_created', table_name='tasks')
    op.drop_index('ix_tasks_batch_status', table_name='tasks')
    op.drop_table('tasks')
    # ### end Alembic commands ###
