"""add task idempotency fields

Revision ID: 2bcb2dd21e29
Revises: dba25e373ce7
Create Date: 2026-09-19 00:44:00.958515
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2bcb2dd21e29'
down_revision: Union[str, Sequence[str], None] = 'dba25e373ce7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks') as batch_op:
        batch_op.add_column(sa.Column('resource_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('idempotency_key', sa.String(length=200), nullable=True))
        batch_op.create_unique_constraint('uq_tasks_batch_type_idempotency', ['batch_id', 'task_type', 'idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks') as batch_op:
        batch_op.drop_constraint('uq_tasks_batch_type_idempotency', type_='unique')
        batch_op.drop_column('idempotency_key')
        batch_op.drop_column('resource_id')
    # ### end Alembic commands ###
