const { chromium } = require('C:/Users/13535/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert = require('node:assert/strict');
const { pathToFileURL } = require('node:url');
const path = require('node:path');
const fs = require('node:fs');
const results=[];
const mark=s=>{results.push(s);console.log('PASS '+s)};
(async()=>{
 const browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});
 const context=await browser.newContext({viewport:{width:1440,height:1000}});
 const page=await context.newPage(); const errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 page.on('dialog',d=>d.accept());
 const click=async(action,id)=>page.locator('[data-action="'+action+'"]'+(id?'[data-id="'+id+'"]':'')).first().click();
 const data=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('pixiaozhi.prototype.v2')));
 const value=async(selector,text)=>page.locator(selector).fill(String(text));
 await page.goto(pathToFileURL(path.resolve('prototype.html')).href);
 await page.locator('#login-email').fill('teacher@example.com'); await page.locator('#login-password').fill('123456'); await page.locator('#login-form').press('Enter');
 await page.getByRole('heading',{name:'你好，林老师'}).waitFor();
 assert.equal(await page.locator('#nav button').count(),6); mark('初始化、空状态、无独立 OCR 导航');
 await click('demo'); await page.getByRole('button',{name:'英语练习 · 演示数据',exact:true}).waitFor();
 let s=await data(), b=s.batches[0];
 await click('ocr-open',b.id); await page.locator('#original-preview img').waitFor();
 assert(await page.locator('#original-preview img').evaluate(i=>i.complete&&i.naturalWidth>0));
 await page.locator('#ocr-form button[value="confirm"]').click();
 await click('grading-open',b.id); await click('run-grade');
 s=await data();assert.equal(Object.keys(s.batches[0].grades).length,2);mark('演示原图、按题校对、客观规则与主观模拟初评');
 await page.locator('#grade-form button[value="confirm"]').click();
 await value('#g-point-0',7);
 await page.locator('#grade-form button[value="confirm"]').click();
 s=await data();assert.equal(Object.values(s.batches[0].grades).filter(g=>g.reviewed).length,1);
 await value('#g-point-0',6);await value('#g-point-1',5);await value('#g-point-2',3);
 await page.locator('#grade-form button[value="confirm"]').click();
 await page.locator('.form-errors').waitFor();
 await value('#g-reason','根据原图逐点评分');await page.locator('#grade-form button[value="confirm"]').click();
 s=await data();assert.equal(Object.values(s.batches[0].grades).filter(g=>g.reviewed).length,2);mark('分数上限、修改原因、逐题复核与分项求和');
 await click('nav','reports');assert((await page.locator('#view').innerText()).includes('19'));
 await page.locator('#report-mode').selectOption('ai');assert((await page.locator('#view').innerText()).includes('15'));
 await page.locator('#report-mode').selectOption('reviewed');
 await click('student-report');await click('report-to-grade');await page.locator('#grade-form').waitFor();mark('正式/初评报告分离及学生明细回溯');
 await click('nav','assignments');await click('ocr-open',b.id);await value('#a-text-0','B');await page.locator('#ocr-form button[value="confirm"]').click();
 s=await data();let grades=Object.values(s.batches[0].grades);assert.equal(grades.filter(g=>g.stale).length,1);assert.equal(grades.filter(g=>g.reviewed).length,1);
 await click('nav','reports');assert((await page.locator('#view').innerText()).includes('未完成，不计总分'));mark('修改一题只失效该题，旧总分退出正式报告');
 await click('nav','rubrics');await click('rubric-edit',s.rubrics[0].id);await value('#r-name','新版演示标准');await page.locator('#rubric-form button[type=submit]').click();
 s=await data();assert.equal(s.rubrics[0].version,2);assert.equal(Object.values(s.batches[0].grades).filter(g=>g.stale).length,2);mark('评分标准版本更新与关联失效');
 await click('nav','assignments');await click('classes');await value('#class-name','测试七年级');await value('#class-students','001,张三\n001,李四');await page.locator('#class-form button[type=submit]').click();await page.locator('.form-errors').waitFor();
 await value('#class-students','001,张三\n002,李四');await page.locator('#class-form button[type=submit]').click();
 s=await data();const cls=s.classes.find(c=>c.name==='测试七年级');assert.equal(cls.students.length,2);mark('班级名单保存与学号去重');
 await click('batch-edit');await value('#b-title','<img src=x onerror=alert(1)> 测试批次');await page.locator('#b-class').selectOption(cls.id);await page.locator('#b-subject').selectOption('数学');await value('#q-answer-0','42');await page.locator('#batch-form button[value=draft]').click();
 s=await data();b=s.batches[0];assert.equal(b.draft,true);assert.equal(await page.locator('#batch-results img').count(),0);
 await click('batch-open',b.id);assert.equal(await page.locator('#q-answer-0').inputValue(),'42');await value('#b-title','数学测试A');await page.locator('#batch-form button[value=upload]').click();await page.locator('#upload-files').waitFor();
 s=await data();assert.equal(s.batches.filter(x=>x.id===b.id).length,1);assert.equal(s.batches[0].draft,false);mark('草稿回填、原批次更新、保存后上传、HTML 注入转义');
 const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aV1sAAAAASUVORK5CYII=','base64');
 await page.locator('#upload-files').setInputFiles([{name:'张三_page1.png',mimeType:'image/png',buffer:png},{name:'invalid.jpg',mimeType:'image/jpeg',buffer:Buffer.from('not an image')}]);
 await page.waitForFunction(()=>!document.querySelector('#upload-files').disabled);
 s=await data();b=s.batches.find(x=>x.id===b.id);assert.equal(b.files.filter(f=>f.status==='success').length,1);assert.equal(b.files.filter(f=>f.status==='failed').length,1);assert.equal(b.pages[0].studentId,'');mark('文件内容校验、成功失败逐项记录、不套用演示学生');
 await click('upload-next');await page.locator('#ocr-student').selectOption(cls.students[0].id);await page.locator('#a-present-0').check();await value('#a-text-0','42');await page.locator('#ocr-form button[value=confirm]').click();
 await click('grading-open',b.id);await click('run-grade');await page.locator('#grade-form button[value=confirm]').click();await click('nav','reports');assert((await page.locator('#view').innerText()).includes('100'));mark('真实上传文件 → 指定学生 → 规则判分 → 正式报告');
 await page.reload();s=await data();assert.equal(s.batches.find(x=>x.id===b.id).grades[cls.students[0].id+':'+b.questions[0].id].score,100);
 await click('nav','assignments');await click('ocr-open',b.id);await page.locator('#original-preview img').waitFor();mark('刷新恢复答案、分数和 IndexedDB 原图');
 await click('nav','assignments');await click('batch-edit');await value('#b-title','数学测试B');await page.locator('#b-class').selectOption(cls.id);await page.locator('#b-subject').selectOption('数学');await value('#q-answer-0','0');await page.locator('#batch-form button[value=upload]').click();
 await page.locator('#upload-files').setInputFiles([{name:'李四.png',mimeType:'image/png',buffer:png}]);await page.waitForFunction(()=>!document.querySelector('#upload-files').disabled);await click('upload-next');
 assert((await page.locator('#breadcrumb').innerText()).includes('数学测试B'));assert.equal(await page.locator('#ocr-student').inputValue(),'');assert.equal(await page.locator('#a-text-0').inputValue(),'');mark('跨批次文件、学生和答案隔离');
 s=await data();const batchB=s.batches[0];
 await click('nav','assignments');await click('batch-edit',batchB.id);await value('#q-answer-0','42');
 await page.locator('#reference-file').setInputFiles({name:'参考答案.png',mimeType:'image/png',buffer:png});await page.locator('#reference-preview img').waitFor();await click('reference-demo');assert((await page.locator('#reference-preview').innerText()).includes('没有读取图片中的文字'));
 await page.locator('#batch-form button[value=draft]').click();s=await data();assert.equal(s.batches[0].draft,false);
 await click('batch-edit',batchB.id);await page.locator('#reference-preview img').waitFor();await click('close');mark('参考答案图片保留、模拟边界、已上传批次保存不退回草稿');
 await click('ocr-open',batchB.id);await page.locator('#ocr-student').selectOption(cls.students[1].id);await page.locator('#a-present-0').check();await value('#a-text-0','4');await page.locator('#ocr-form button[value=confirm]').click();
 await click('upload',batchB.id);await page.locator('#upload-files').setInputFiles({name:'李四_page2.png',mimeType:'image/png',buffer:png});await page.waitForFunction(()=>!document.querySelector('#upload-files').disabled);await click('upload-next');
 s=await data();const second=s.batches[0].pages[1];await page.locator('#ocr-page').selectOption(second.id);await page.locator('#ocr-student').selectOption(cls.students[1].id);await page.locator('#a-present-0').check();await value('#a-text-0','2');await page.locator('#ocr-form button[value=confirm]').click();await page.locator('.form-errors').waitFor();
 await value('#ocr-sequence',3);await page.locator('#ocr-form button[value=confirm]').click();await click('grading-open',batchB.id);await click('run-grade');await page.locator('#dialog').waitFor({state:'visible'});assert((await page.locator('#dialog').innerText()).includes('页序重复或不连续'));await click('close');
 await click('ocr-open',batchB.id);await page.locator('#ocr-page').selectOption(second.id);await value('#ocr-sequence',2);await page.locator('#ocr-form button[value=confirm]').click();await click('grading-open',batchB.id);await click('run-grade');
 s=await data();let bg=Object.values(s.batches[0].grades)[0];assert.equal(bg.input,'4\n2');assert.equal(bg.suggested,100);mark('重复页序拦截、缺页阻断、多页同学生按页序合并');
 await click('ocr-open',batchB.id);await page.locator('#ocr-page').selectOption(second.id);await value('#a-text-0','');await page.locator('#a-blank-0').check();await page.locator('#ocr-form button[value=confirm]').click();await click('grading-open',batchB.id);await click('run-grade');assert((await page.locator('#dialog').innerText()).includes('跨页存在空题与有答案冲突'));await click('close');mark('跨页空题和有效答案冲突不能静默判分');
 await click('nav','assignments');await click('upload',b.id);s=await data();const failed=s.batches.find(x=>x.id===b.id).files.find(f=>f.status==='failed');
 const chooserPromise=page.waitForEvent('filechooser');await click('retry-file',failed.id);const chooser=await chooserPromise;await chooser.setFiles({name:'修复文件.png',mimeType:'image/png',buffer:png});await page.waitForFunction(()=>!document.querySelector('#upload-files').disabled);s=await data();assert.equal(s.batches.find(x=>x.id===b.id).files.find(f=>f.id===failed.id).status,'success');
 const count=s.batches.find(x=>x.id===b.id).files.length;await page.locator('#upload-files').setInputFiles({name:'修复文件.png',mimeType:'image/png',buffer:png});await page.waitForFunction(()=>!document.querySelector('#upload-files').disabled);s=await data();assert.equal(s.batches.find(x=>x.id===b.id).files.length,count);await click('close');mark('失败项重新选择文件重试与重复文件跳过');
 const pdfPage=await context.newPage();await pdfPage.setContent('<h1>PDF upload test</h1>');const pdf=await pdfPage.pdf();await pdfPage.close();
 await click('upload',batchB.id);await page.locator('#upload-files').setInputFiles({name:'多页作业.pdf',mimeType:'application/pdf',buffer:pdf});await page.waitForFunction(()=>!document.querySelector('#upload-files').disabled);await click('upload-next');s=await data();let pdfFirst=s.batches.find(x=>x.id===batchB.id).pages.find(p=>s.batches.find(x=>x.id===batchB.id).files.find(f=>f.id===p.fileId).type==='application/pdf');
 await page.locator('#ocr-page').selectOption(pdfFirst.id);await click('pdf-pages');await value('#pdf-count',2);await page.locator('#pdf-form button[type=submit]').click();s=await data();assert.equal(s.batches.find(x=>x.id===batchB.id).pages.filter(p=>p.fileId===pdfFirst.fileId).length,2);await page.reload();assert((await page.locator('#breadcrumb').innerText()).includes('数学测试B'));assert.equal(await page.locator('#ocr-page').inputValue(),pdfFirst.id);mark('PDF 上传、人工拆分页记录、刷新保留当前批次与页面');
 await page.locator('#ocr-student').selectOption(cls.students[0].id);await page.locator('#a-present-0').check();await value('#a-text-0','尚未保存');page.removeAllListeners('dialog');page.on('dialog',d=>d.dismiss());await click('nav','reports');assert.equal(await page.locator('#a-text-0').inputValue(),'尚未保存');page.removeAllListeners('dialog');page.on('dialog',d=>d.accept());await click('nav','reports');mark('未保存内容离开警告及取消离开保留输入');
 for(const width of [375,768,1024,1440]){await page.setViewportSize({width,height:1000});for(const route of ['workbench','assignments','ocr','grading','rubrics','reports','settings']){await page.evaluate(route=>navigate(route),route);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'overflow '+route+' '+width)}mark('全部页面无横向溢出 '+width+'px')}
 await page.setViewportSize({width:1440,height:1000});await page.evaluate(()=>navigate('assignments'));await click('batch-edit');await page.keyboard.press('Escape');assert.equal(await page.locator('#dialog').evaluate(d=>d.open),false);mark('弹窗 Escape 关闭');
 await click('nav','settings');await value('#teacher-name','测试老师');await page.locator('#settings-form button[type=submit]').click();await page.reload();assert.equal(await page.locator('#teacher-name').inputValue(),'测试老师');mark('教师配置保存与刷新');
 await page.evaluate(()=>navigate('assignments'));await click('batch-edit');await page.keyboard.press('Shift+Tab');assert(await page.evaluate(()=>document.querySelector('#dialog').contains(document.activeElement)));await page.keyboard.press('Escape');mark('原生弹窗键盘焦点圈定');
 await value('#batch-search','数学测试B');assert.equal(await page.locator('.batch-table tbody tr').count(),1);await click('reset-search');await page.locator('#subject-filter').selectOption('语文');assert((await page.locator('#batch-results').innerText()).includes('没有符合筛选'));await click('reset-search');await value('#global-search','李四');await page.locator('#global-search').press('Enter');assert.equal(await page.locator('.batch-table tbody tr').count(),2);await click('reset-search');await click('records');assert((await page.locator('#dialog').innerText()).includes('修复文件.png'));await click('close');mark('批次筛选、全局学生搜索、上传记录');
 await click('nav','rubrics');s=await data();await click('rubric-history',s.rubrics[0].id);assert((await page.locator('#dialog').innerText()).includes('当前版本'));await click('close');await click('rubric-toggle',s.rubrics[0].id);assert.equal((await data()).rubrics[0].active,false);await click('rubric-toggle',s.rubrics[0].id);await click('rubric-edit');await value('#r-name','不合法标准');await value('#r-total',100);await page.locator('#rubric-form button[type=submit]').click();await page.locator('.form-errors').waitFor();await click('close');mark('标准启停、版本历史、评分点总分校验');
 await click('nav','assignments');await click('batch-edit',batchB.id);await value('#b-total',99);await page.locator('#batch-form button[value=draft]').click();await click('nav','grading');await click('run-grade');assert((await page.locator('#dialog').innerText()).includes('所有题目分值之和必须等于批次总分'));await click('close');await click('nav','assignments');await click('batch-edit',batchB.id);await value('#b-total',100);await page.locator('#batch-form button[value=draft]').click();mark('批次总分与单题分值合计不符时阻止批改');
 await page.setViewportSize({width:375,height:900});assert(await page.locator('#sidebar').evaluate(e=>e.inert));await page.locator('.topbar [data-action=menu]').click();assert(!(await page.locator('#sidebar').evaluate(e=>e.inert)));await click('nav','assignments');assert(await page.locator('#sidebar').evaluate(e=>e.inert));await page.screenshot({path:'prototype-audit-mobile.png',fullPage:true});await page.setViewportSize({width:1440,height:1000});mark('手机导航展开/收起及隐藏导航禁止键盘聚焦');
 const other=await context.newPage();await other.goto(page.url());await other.evaluate(()=>{const k='pixiaozhi.prototype.v2';const v=JSON.parse(localStorage.getItem(k));v.revision++;localStorage.setItem(k,JSON.stringify(v))});await page.locator('#storage-error').waitFor({state:'visible'});assert((await page.locator('#storage-error').innerText()).includes('另一个标签页'));await other.close();await page.reload();mark('跨标签页修改阻止旧页面覆盖');
 assert.deepEqual(errors,[]);mark('浏览器运行无未捕获脚本异常');
 await page.screenshot({path:'prototype-audit-desktop.png',fullPage:true});
 fs.writeFileSync('prototype-audit-results.json',JSON.stringify({time:new Date().toISOString(),results,errors},null,2));
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
